#!/usr/bin/env bash

# This tool is meant as an aid to mentors reviewing a
# student's submission. It will:
# 1. download the exercise (this should place it in the
#    "users/" subdirectory of your exercism workspace)
# 2. run a syntax checker on the code, if you have one installed locally
# 3. check github for the existance of mentor notes.
# 4. show the code and ask if you want to run the tests
# 5. launch an interactive tclsh shell, so you can
#    play with the solution

shopt -s extglob

########################################################################
main() {
    local uuid workdir slug
    local uuid_re='[[:alnum:]]{32}'

    if [[ "$*" =~ ($uuid_re) ]]; then
        uuid=${BASH_REMATCH[1]}
    else
        echo "usage: $0 <uuid>"
        echo "       $0 exercism download --uuid=<uuid>"
        echo "downloads the submission, runs tests and shellcheck"
        exit
    fi

    echo "=== 1 ==="
    download "$uuid" workdir

    cd "$workdir" || exit 2
    slug=${workdir##*/}
    [[ -f "$slug.tcl" ]] || die "This solution has no source file"
    [[ -f "$slug.test" ]] || die "This solution has no test file"

    # don't start logging until we have a workdir
    { date
      echo "solution: https://exercism.io/mentor/solutions/$uuid"
    } >"$workdir/mentcl.log"
    log_start "$workdir/mentcl.log"

    echo "=== 2 ==="
    run_syntax_check "$slug"

    echo "=== 3 ==="
    mentor_notes_link "$slug"

    echo "=== 4 ==="
    run_tests "$slug"

    echo "=== 5 ==="
    echo "Launching an interactive tclsh in $PWD"
    log_stop
    if command -v rlwrap >/dev/null; then
        exec rlwrap tclsh
    else
        exec tclsh
    fi
}

########################################################################
die() { echo "$*" >&2; exit 1; }

do_exercism() {
    if ! exercism "$@" 2>&1; then
        die "Error: exercism $* failed"
    fi
}

log_start() {
    local logfile=$1
    # store the current file descriptors 1 and 2
    exec 8>&1
    exec 9>&2
    # tee the output on fd 1 and 2 to logfile.
    # Due to buffering, stdout and stderr may appear out of order.
    exec 1> >(tee -a "$logfile")
    exec 2> >(tee -a "$logfile")
}

log_stop() {
    # turn off logging: restore fd 1 and 2
    exec 1>&8
    exec 2>&9
    # close fd 8 and 9
    exec 8>&-
    exec 9>&-
}

yn() {
    [[ $MENTCL_PROMPT_REPLY == "yes to all" ]] && return 0
    local OPTIND yn=yn def="" prompt
    local -u ans
    while getopts :YN opt; do
        case $opt in
            Y) yn="Yn"; def=Y ;;
            N) yn="yN"; def=N ;;
            *) : ;; # ignored
        esac
    done
    shift $((OPTIND-1))
    prompt=${1:-"Yes or no"}
    read -p "$prompt [$yn]? " -e -i "$def" -r ans
    [[ ${ans#+([[:space:]])} == Y* ]]
}

########################################################################
download() {
    local uuid=$1
    local -n dir=$2
    local -a output

    yn -Y "Download solution from https://exercism.io/mentor/solutions/$uuid" || exit

    output=$( do_exercism download --uuid="$uuid" ) || exit 1
    echo "$output"
    dir=${output##*$'\n'}       # last line

    if [[ ! -d $dir ]]; then
        die "Error: could not find the download directory in exercism output"
    fi
}

########################################################################
run_syntax_check() {
    local file="$1.tcl"
    if [[ -z $SYNTAX_CHECKER ]] || ! type "$SYNTAX_CHECKER" >/dev/null; then
        echo "No syntax checker available"
    elif yn -Y "Run syntax checker"; then
        syntax_check "$file"
    fi
}

do_syntax_check() {
    echo "Define this in your ~/.config/exercism/mentclrc file"
}

########################################################################
mentor_notes_link() {
    local slug=$1
    local notes_url curl_opts http_status

    if ! type -p curl >/dev/null; then
        echo "Can't find curl in the PATH."
        return
    fi

    notes_url="https://raw.githubusercontent.com/exercism/website-copy/master/tracks/tcl/exercises/$slug/mentoring.md"
    curl_opts=( --silent --head --write-out '%{http_code}' )
    http_status=$( curl "${curl_opts[@]}" "$notes_url" | tail -1 )

    case $http_status in
        200) echo "Mentor notes: $notes_url" ;;
        404) echo "No mentor notes for $slug" ;;
        *)   echo "Unexpected query status from github: $http_status" ;;
    esac
}

########################################################################
run_tests() {
    local slug=$1
    cat << END_TESTING
Next step is testing:
I will not do that automatically.
*******************************************
*** Make sure you're reviewed the code, ***
*** and that it is non-malicious!       ***
*******************************************
END_TESTING

    yn -Y "Display the code" || return
    displayCode "$slug.tcl"

    echo "*******************************************"
    yn "OK to run tests" || return

    SECONDS=0
    echo
    time tclsh "$slug.test"
    echo
}

# Default function to display the code.
# Can be overridden in the config file if you want a different output.
displayCode() {
    cat -n "$1"
}

usage() {
    echo "usage: $0 [-h] [-y] some_test_containing_a_UUID" >&2
    exit "${1:-0}"
}

########################################################################
# mentcl config: a place to put variables and functions that can be used
# * in this script (such as MENTCL_PROMPT_REPLY)
# * in the environment of the spawned interactive shell
#   (such as RUN_ALL) - don't forget to `export`

exercism_config=$( do_exercism configure ) || exit 1
config_dir=$( sed -nE '/^Config dir: +/s///p' <<< "$exercism_config" )
if [[ -r "$config_dir/mentclrc" ]]; then
    # shellcheck disable=SC1090
    . "$config_dir/mentclrc"
fi

while getopts :hy opt; do
    case $opt in
        h) usage ;;
        y) MENTCL_PROMPT_REPLY="yes to all" ;;
        *) usage 1 ;;
    esac
done
shift $((OPTIND - 1))

main "$@"
