#!/usr/bin/env bash

# We'll be handed the list of files added/modified in a PR.
# From that, extract the list of exercise directories, and
# test there.

minorVer=$(IFS="."; echo "${BASH_VERSINFO[*]:0:2}")

if [[ $minorVer < "4.3" ]]; then
    echo "[Failure] This script requires bash version 4.3+" >&2
    exit 1
fi

declare -A seen=()
status=0

for file; do
    # find the first 3 parts of the path.
    # e.g. if $file is "exercises/practice/hello-world/.meta/example.tcl
    # then $dir should be "exercises/practice/hello-world" 
    IFS=/ read -ra path <<<"$file"
    dir=$(IFS="/"; echo "${path[*]:0:3}")

    [[ $dir == exercises/* ]] || continue

    if [[ ! -v seen["$dir"] ]]; then
        seen["$dir"]=1
        bin/test_one_exercise "$dir" || status=1
    fi
done

exit $status
