#!/usr/bin/env bash

# We'll be handed the list of files added/modified in a PR.
# From that, extract the list of exercise directories, and
# test there.

die() { echo "$*" >&2; exit 1; }

minorVer="${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}"
if [[ $minorVer < "4.3" ]]; then
    die "[Failure] This script requires bash version 4.3+" >&2
fi

declare -A seen=()
status=0

for file; do
    dir=$(dirname "$file")
    if [[ ! -v seen["$dir"] ]]; then
        seen["$dir"]=1
        bin/test_one_exercise "$(basename "$dir")" || status=1
    fi
done

exit $status
