# Run all tests for commits to master

name: tcl / ci-test-all

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-24.04
    container:
      image: exercism/tcl-test-runner:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Run tests for all exercises
        run: bin/verify-in-test-runner.tcl
